name: Release Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  release_linux:
    name: Linux Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create Build Directory
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Install Packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends gcc-multilib libsdl2-dev libsdl2-mixer-dev libsdl2-image-dev libsdl2-ttf-dev

      - name: Configure CMake
        run: cmake .

      - name: Build
        run: make

      - name: Create Artifact
        run: |
          mkdir release
          cp wakawaka release/wakawaka

      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-release
          path: release

  release_windows:
    name: Windows Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create Build Directory
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Install Packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends mingw-w64 libsdl2-dev libsdl2-mixer-dev libsdl2-image-dev libsdl2-ttf-dev

      - name: Configure CMake
        run: cmake -DCMAKE_TOOLCHAIN_FILE=TC-mingw.cmake .

      - name: Build
        run: make

      - name: Create Artifact
        run: |
          mkdir release
          cp wakawaka release/wakawaka

      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-release
          path: release
